export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-12 px-4">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      
      <div className="prose dark:prose-invert">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using this AI chat service, you agree to be bound by these Terms of Service.
          If you do not agree to these terms, please do not use the service.
        </p>

        <h2>2. Service Description</h2>
        <p>
          We provide an AI-powered chat service that aims to assist users with various queries and tasks.
          The service utilizes artificial intelligence to generate responses and process user inputs.
        </p>

        <h2>3. User Responsibilities</h2>
        <ul>
          <li>You must use the service in compliance with all applicable laws and regulations</li>
          <li>You are responsible for maintaining the confidentiality of your account</li>
          <li>You agree not to misuse or attempt to disrupt the service</li>
        </ul>

        <h2>4. AI Generated Content</h2>
        <p>
          The content generated by our AI system is provided "as is" without any warranties.
          While we strive for accuracy, we cannot guarantee that all information provided is complete,
          accurate, or suitable for any particular purpose.
        </p>

        <h2>5. Limitations of Liability</h2>
        <p>
          We shall not be liable for any direct, indirect, incidental, special, or consequential
          damages resulting from the use or inability to use the service.
        </p>

        <h2>6. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Continued use of the service
          after such modifications constitutes acceptance of the updated terms.
        </p>

        <h2>7. Contact Information</h2>
        <p>
          If you have any questions about these Terms of Service, please contact us at:
          support@codxai.com
        </p>

        <p>By using CodXai&apos;s AI assistant, you acknowledge that the AI may generate &ldquo;hallucinations&rdquo; or inaccurate information.</p>
      </div>
    </div>
  );
} 